GET  http://localhost:5000/api/Notes/fetchallnotes
Content-Type: application/json
auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjhlZDRiYmM0NWUyNGZhZGRkZjUwN2ExIn0sImlhdCI6MTc2MDQzNjQxNn0.5ZdWR_uM1boWrD--NojmtUVBneG4zuPCZmr1jhQSPz8



